
[machines]

	[machines.split_tank]
		#Range: 1000 ~ 32767
		fluid_storage = 3000
		#Range: 1 ~ 32767
		mix_usage = 100
		#Range: 1 ~ 32767
		bio_diesel_generation = 100
		#Range: 10 ~ 32767
		generating_time = 800
		#Range: 1 ~ 32767
		glycerin_generation = 10

	[machines.oil_mill]
		#Range: 1000 ~ 32767
		fluid_storage = 3000
		#Range: 1000 ~ 32767
		energy_storage = 10000
		#Range: 1 ~ 32767
		energy_usage = 10
		#Range: 1 ~ 32767
		fluid_generation = 100
		#Range: 10 ~ 32767
		generating_time = 200

	[machines.backmix_reactor]
		#Range: 1000 ~ 32767
		fluid_storage = 3000
		#Range: 1 ~ 32767
		methanol_usage = 50
		#Range: 1 ~ 32767
		mix_generation = 100
		#Range: 100 ~ 32767
		energy_storage = 10000
		#Range: 1 ~ 32767
		canola_usage = 50
		#Range: 1 ~ 32767
		energy_usage = 10
		#Range: 10 ~ 32767
		generating_time = 200

	[machines.generator]
		#Range: 1000 ~ 32767
		fluid_storage = 3000
		#Range: 1 ~ 32767
		energy_generation = 500
		#Range: 1000 ~ 32767
		energy_storage = 30000

	[machines.fuel_station]
		#Range: 1 ~ 32767
		transfer_rate = 5
		valid_fuels = ["car:bio_diesel"]

	[machines.dynamo]
		#Range: 1 ~ 32767
		energy_generation = 25
		#Range: 100 ~ 32767
		energy_storage = 1000

	[machines.cable]
		#Range: 64 ~ 32767
		transfer_rate = 256

	[machines.blast_furnace]
		#Range: 1000 ~ 32767
		fluid_storage = 3000
		#Range: 1000 ~ 32767
		energy_storage = 10000
		#Range: 1 ~ 32767
		energy_usage = 10
		#Range: 1 ~ 32767
		fluid_generation = 100
		#Range: 10 ~ 32767
		generating_time = 200

	[machines.fluid_extractor]
		#Range: 5 ~ 32767
		drain_speed = 25

[items]

	[items.repair_kit]
		#Range: 0.10000000149011612 ~ 100.0
		repair_amount = 5.0

	[items.canister]
		#Range: 1 ~ 1000
		max_fuel = 100

[car]
	#True if starting the car should use battery
	use_battery = true
	valid_fuels = ["car:bio_diesel"]
	#Whether the cars should collide with other entities (except cars)
	collide_with_entities = false
	#Whether animals flee from the car when the horn is activted
	horn_flee = true
	#Whether the cars should damage other entities on collision
	damage_entities = true
	#Whether the cars drive slower on non road blocks
	road_blocks_enabled = false

	[car.road_blocks]
		blocks = ["car:asphalt", "car:asphalt_slab", "car:asphalt_slope", "car:asphalt_slope_flat_lower", "car:asphalt_slope_flat_upper"]

