
#General Settings
[general]
	#The list of slabs (or tags) and variants to ignore when creating double slabs
	#Example: minecraft:purpur_slab
	slab_blacklist = []
	#Whether to disable the placement of vertical slabs from regular horizontal slabs when holding shift
	disable_vertical_slab_placement = false
	#Whether to use an alternate system when placing vertical slabs
	alternate_vertical_slab_placement = true
	#The list of slabs (or tags) to ignore when creating vertical slabs
	#Example: minecraft:purpur_slab
	vertical_slab_blacklist = []
	#Whether to use the custom double slab when combining slabs of the same type
	replace_same_slab = true

